name: "T875"
on:
  push:
    branches: '**'
  workflow_dispatch:

jobs:
  build:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout kernel source
      uses: actions/checkout@v2

    - run: |
        mv .git ../
        rm -rf *
        git clone https://github.com/iamSlightlyWind/T875_BUK2
        cd T875_BUK2
        git checkout base
    
    - name: Debug with SSH
      uses: iamSlightlyWind/ssh-server-action@v1
      with:
        ngrok-authtoken: "1uPm1SyJG3xrEcXvnXqQjFevx1O_5ExNcT6ibyJJrTGHZmtoA"
        ssh-public-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPcdw+kXvwnBQQu1LR4whI233bzo6b+EHb/ZdV9eIqOe iamSlightlyWind@themajorones.dev"